In [181]:
import yfinance as yf
import numpy as np
import pandas as pd
import scipy.stats
from pandas.core.arrays import period
from datetime import datetime

In [182]:
ticker = yf.Ticker("AAPL")

In [183]:
expiry_date = ticker.options[0]
T = (datetime.strptime(expiry_date, "%Y-%m-%d").date() - datetime.today().date()).days
print(T)

0

In [184]:
if T == 0:
  expiry_date = ticker.options[1]
  T = (datetime.strptime(expiry_date, "%Y-%m-%d").date() - datetime.today().date()).days
print(T)
T = T/365
T

4

0.010958904109589041

In [185]:
print(ticker.info)

{'address1': 'One Apple Park Way', 'city': 'Cupertino', 'state': 'CA', 'zip': '95014', 'country': 'United States', 'phone': '(408) 996-1010', 'website': 'https://www.apple.com', 'industry': 'Consumer Electronics', 'industryKey': 'consumer-electronics', 'industryDisp': 'Consumer Electronics', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.', 'fullTimeEmployees': 166000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 64, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2025, 'totalPay': 16759518, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Kevan  Parekh', 'age': 53, 'title': 'Senior VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 4034174, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sabih  Khan', 'age': 58, 'title': 'Senior VP & Chief Operating Officer', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5021905, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 58, 'title': 'Senior Vice President of Retail & People', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5037867, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 61, 'title': 'Senior VP of Government Affairs & Secretary', 'yearBorn': 1964, 'fiscalYear': 2025, 'totalPay': 5022482, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Ben  Borders', 'age': 44, 'title': 'Principal Accounting Officer', 'yearBorn': 1981, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Jennifer G. Newstead J.D.', 'age': 55, 'title': 'Senior VP & General Counsel', 'yearBorn': 1970, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Kristin Huguet Quayle', 'title': 'Vice President of Worldwide Communications', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 2, 'boardRisk': 1, 'compensationRisk': 7, 'shareHolderRightsRisk': 1, 'overallRisk': 1, 'governanceEpochDate': 1780531200, 'compensationAsOfEpochDate': 1767139200, 'irWebsite': 'http://investor.apple.com/', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 299.24, 'open': 300.845, 'dayLow': 294.41, 'dayHigh': 302.07, 'regularMarketPreviousClose': 299.24, 'regularMarketOpen': 300.845, 'regularMarketDayLow': 294.41, 'regularMarketDayHigh': 302.07, 'dividendRate': 1.08, 'dividendYield': 0.36, 'exDividendDate': 1778457600, 'payoutRatio': 0.1259, 'fiveYearAvgDividendYield': 0.5, 'beta': 1.086, 'trailingPE': 35.8293, 'forwardPE': 30.844223, 'volume': 42329351, 'regularMarketVolume': 42329351, 'averageVolume': 47139609, 'averageVolume10days': 52063790, 'averageDailyVolume10Day': 52063790, 'bid': 294.55, 'ask': 296.97, 'bidSize': 12, 'askSize': 4, 'marketCap': 4346723172352, 'nonDilutedMarketCap': 4346723008200, 'fiftyTwoWeekLow': 196.86, 'fiftyTwoWeekHigh': 317.4, 'allTimeHigh': 317.4, 'allTimeLow': 0.049107, 'priceToSalesTrailing12Months': 9.6285305, 'fiftyDayAverage': 287.9578, 'twoHundredDayAverage': 267.85165, 'trailingAnnualDividendRate': 1.04, 'trailingAnnualDividendYield': 0.0034754712, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 4411248607232, 'profitMargins': 0.27152002, 'floatShares': 14662534368, 'sharesOutstanding': 14687356000, 'sharesShort': 155886024, 'sharesShortPriorMonth': 134675274, 'sharesShortPreviousMonthDate': 1777507200, 'dateShortInterest': 1780012800, 'sharesPercentSharesOut': 0.0106, 'heldPercentInsiders': 0.01632, 'heldPercentInstitutions': 0.65825, 'shortRatio': 3.12, 'shortPercentOfFloat': 0.0106, 'impliedSharesOutstanding': 14687356000, 'bookValue': 7.26, 'priceToBook': 40.76446, 'lastFiscalYearEnd': 1758931200, 'nextFiscalYearEnd': 1790467200, 'mostRecentQuarter': 1774656000, 'earningsQuarterlyGrowth': 0.194, 'netIncomeToCommon': 122575003648, 'trailingEps': 8.26, 'forwardEps': 9.59499, 'pegRatio': 2.42, 'lastSplitFactor': '4:1', 'lastSplitDate': 1598832000, 'enterpriseToRevenue': 9.771, 'enterpriseToEbitda': 27.574, '52WeekChange': 0.47238803, 'SandP52WeekChange': 0.24334764, 'lastDividendValue': 0.27, 'lastDividendDate': 1778457600, 'quoteType': 'EQUITY', 'currentPrice': 295.95, 'targetHighPrice': 400.0, 'targetLowPrice': 215.0, 'targetMeanPrice': 312.71628, 'targetMedianPrice': 310.0, 'recommendationMean': 1.97917, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 43, 'totalCash': 68507000832, 'totalCashPerShare': 4.664, 'ebitda': 159975997440, 'totalDebt': 84710998016, 'quickRatio': 0.906, 'currentRatio': 1.07, 'totalRevenue': 451442016256, 'debtToEquity': 79.548, 'revenuePerShare': 30.534, 'returnOnAssets': 0.26229, 'returnOnEquity': 1.4147099, 'grossProfits': 216070995968, 'freeCashflow': 101090746368, 'operatingCashflow': 140222005248, 'earningsGrowth': 0.218, 'revenueGrowth': 0.166, 'grossMargins': 0.47862, 'ebitdaMargins': 0.35437, 'operatingMargins': 0.32275, 'financialCurrency': 'USD', 'symbol': 'AAPL', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 345479400000, 'regularMarketChangePercent': -1.09944, 'regularMarketPrice': 295.95, 'marketState': 'PRE', 'corporateActions': [], 'preMarketTime': 1781785847, 'regularMarketTime': 1781726401, 'exchange': 'NMS', 'messageBoardId': 'finmb_24937', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'shortName': 'Apple Inc.', 'longName': 'Apple Inc.', 'preMarketChange': 0.958374, 'preMarketChangePercent': 0.32382968, 'preMarketPrice': 296.9084, 'regularMarketChange': -3.28998, 'regularMarketDayRange': '294.41 - 302.07', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 47139609, 'fiftyTwoWeekLowChange': 99.09001, 'fiftyTwoWeekLowChangePercent': 0.5033527, 'fiftyTwoWeekRange': '196.86 - 317.4', 'fiftyTwoWeekHighChange': -21.449982, 'fiftyTwoWeekHighChangePercent': -0.06758028, 'fiftyTwoWeekChangePercent': 47.238804, 'dividendDate': 1778716800, 'earningsTimestamp': 1777579200, 'earningsTimestampStart': 1785441600, 'earningsTimestampEnd': 1785441600, 'earningsCallTimestampStart': 1777582800, 'earningsCallTimestampEnd': 1777582800, 'isEarningsDateEstimate': True, 'epsTrailingTwelveMonths': 8.26, 'epsForward': 9.59499, 'epsCurrentYear': 8.75208, 'priceEpsCurrentYear': 33.81482, 'fiftyDayAverageChange': 7.992218, 'fiftyDayAverageChangePercent': 0.027754825, 'twoHundredDayAverageChange': 28.098358, 'twoHundredDayAverageChangePercent': 0.104902685, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '2.0 - Buy', 'cryptoTradeable': False, 'displayName': 'Apple', 'trailingPegRatio': 2.3913}

In [186]:
calls = ticker.option_chain(expiry_date).calls
calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260622C00235000,2026-06-15 15:41:41+00:00,235.0,61.80,0.0,0.0,0.0,0.0,5.0,111,0.000010,True,REGULAR,USD
1,AAPL260622C00240000,2026-06-15 15:41:41+00:00,240.0,56.83,0.0,0.0,0.0,0.0,2.0,129,0.000010,True,REGULAR,USD
2,AAPL260622C00245000,2026-06-12 15:55:14+00:00,245.0,47.25,0.0,0.0,0.0,0.0,59.0,68,0.000010,True,REGULAR,USD
3,AAPL260622C00250000,2026-06-12 15:55:15+00:00,250.0,42.29,0.0,0.0,0.0,0.0,NaN,137,0.000010,True,REGULAR,USD
4,AAPL260622C00255000,2026-06-15 16:47:24+00:00,255.0,42.11,0.0,0.0,0.0,0.0,1.0,71,0.000010,True,REGULAR,USD
5,AAPL260622C00260000,2026-06-17 19:28:51+00:00,260.0,35.42,0.0,0.0,0.0,0.0,9.0,37,0.000010,True,REGULAR,USD
6,AAPL260622C00262500,2026-06-16 16:15:22+00:00,262.5,36.90,0.0,0.0,0.0,0.0,36.0,100,0.000010,True,REGULAR,USD
7,AAPL260622C00265000,2026-06-17 17:08:14+00:00,265.0,32.10,0.0,0.0,0.0,0.0,1.0,93,0.000010,True,REGULAR,USD
8,AAPL260622C00267500,2026-06-17 15:59:37+00:00,267.5,31.03,0.0,0.0,0.0,0.0,64.0,76,0.000010,True,REGULAR,USD
9,AAPL260622C00270000,2026-06-17 15:59:36+00:00,270.0,28.67,0.0,0.0,0.0,0.0,54.0,147,0.000010,True,REGULAR,USD
10,AAPL260622C00272500,2026-06-15 18:26:33+00:00,272.5,23.47,0.0,0.0,0.0,0.0,2.0,28,0.000010,True,REGULAR,USD
11,AAPL260622C00275000,2026-06-17 15:35:15+00:00,275.0,22.71,0.0,0.0,0.0,0.0,2.0,27,0.000010,True,REGULAR,USD
12,AAPL260622C00277500,2026-06-17 15:19:35+00:00,277.5,20.65,0.0,0.0,0.0,0.0,1.0,109,0.000010,True,REGULAR,USD
13,AAPL260622C00280000,2026-06-17 18:12:32+00:00,280.0,16.45,0.0,0.0,0.0,0.0,33.0,210,0.000010,True,REGULAR,USD
14,AAPL260622C00282500,2026-06-17 15:48:17+00:00,282.5,14.78,0.0,0.0,0.0,0.0,87.0,112,0.000010,True,REGULAR,USD
15,AAPL260622C00285000,2026-06-17 19:17:46+00:00,285.0,11.20,0.0,0.0,0.0,0.0,45.0,62,0.000010,True,REGULAR,USD
16,AAPL260622C00287500,2026-06-17 19:47:48+00:00,287.5,8.30,0.0,0.0,0.0,0.0,34.0,82,0.000010,True,REGULAR,USD
17,AAPL260622C00290000,2026-06-17 19:47:47+00:00,290.0,6.20,0.0,0.0,0.0,0.0,259.0,399,0.000010,True,REGULAR,USD
18,AAPL260622C00292500,2026-06-17 19:59:47+00:00,292.5,5.00,0.0,0.0,0.0,0.0,44.0,302,0.000010,True,REGULAR,USD
19,AAPL260622C00295000,2026-06-17 19:59:41+00:00,295.0,3.36,0.0,0.0,0.0,0.0,1133.0,1254,0.000010,True,REGULAR,USD
20,AAPL260622C00297500,2026-06-17 19:59:59+00:00,297.5,2.15,0.0,0.0,0.0,0.0,5056.0,2460,0.015635,False,REGULAR,USD
21,AAPL260622C00300000,2026-06-17 19:59:59+00:00,300.0,1.36,0.0,0.0,0.0,0.0,10086.0,4413,0.031260,False,REGULAR,USD
22,AAPL260622C00302500,2026-06-17 19:59:49+00:00,302.5,0.76,0.0,0.0,0.0,0.0,3515.0,1021,0.062509,False,REGULAR,USD
23,AAPL260622C00305000,2026-06-17 19:59:52+00:00,305.0,0.47,0.0,0.0,0.0,0.0,4693.0,2397,0.062509,False,REGULAR,USD
24,AAPL260622C00307500,2026-06-17 19:59:33+00:00,307.5,0.26,0.0,0.0,0.0,0.0,2176.0,969,0.062509,False,REGULAR,USD
25,AAPL260622C00310000,2026-06-17 19:59:16+00:00,310.0,0.15,0.0,0.0,0.0,0.0,1971.0,1470,0.125009,False,REGULAR,USD
26,AAPL260622C00312500,2026-06-17 19:57:22+00:00,312.5,0.08,0.0,0.0,0.0,0.0,143.0,722,0.125009,False,REGULAR,USD
27,AAPL260622C00315000,2026-06-17 19:57:09+00:00,315.0,0.09,0.0,0.0,0.0,0.0,1297.0,1220,0.125009,False,REGULAR,USD
28,AAPL260622C00317500,2026-06-17 18:43:09+00:00,317.5,0.04,0.0,0.0,0.0,0.0,107.0,339,0.125009,False,REGULAR,USD
29,AAPL260622C00320000,2026-06-17 18:48:25+00:00,320.0,0.04,0.0,0.0,0.0,0.0,165.0,576,0.125009,False,REGULAR,USD
30,AAPL260622C00322500,2026-06-17 15:06:07+00:00,322.5,0.03,0.0,0.0,0.0,0.0,35.0,53,0.125009,False,REGULAR,USD
31,AAPL260622C00325000,2026-06-17 18:04:44+00:00,325.0,0.02,0.0,0.0,0.0,0.0,724.0,866,0.125009,False,REGULAR,USD
32,AAPL260622C00327500,2026-06-11 16:11:28+00:00,327.5,0.07,0.0,0.0,0.0,0.0,NaN,5,0.250007,False,REGULAR,USD
33,AAPL260622C00330000,2026-06-16 19:22:55+00:00,330.0,0.02,0.0,0.0,0.0,0.0,8.0,83,0.250007,False,REGULAR,USD
34,AAPL260622C00332500,2026-06-16 17:20:13+00:00,332.5,0.01,0.0,0.0,0.0,0.0,1.0,6,0.250007,False,REGULAR,USD
35,AAPL260622C00335000,2026-06-17 13:40:53+00:00,335.0,0.02,0.0,0.0,0.0,0.0,1.0,216,0.250007,False,REGULAR,USD
36,AAPL260622C00340000,2026-06-16 14:50:17+00:00,340.0,0.01,0.0,0.0,0.0,0.0,4.0,128,0.250007,False,REGULAR,USD
37,AAPL260622C00345000,2026-06-17 15:26:30+00:00,345.0,0.01,0.0,0.0,0.0,0.0,126.0,495,0.250007,False,REGULAR,USD
38,AAPL260622C00350000,2026-06-16 17:02:57+00:00,350.0,0.02,0.0,0.0,0.0,0.0,2.0,57,0.250007,False,REGULAR,USD
39,AAPL260622C00355000,2026-06-17 18:47:17+00:00,355.0,0.01,0.0,0.0,0.0,0.0,1.0,4,0.250007,False,REGULAR,USD
40,AAPL260622C00360000,2026-06-17 18:19:46+00:00,360.0,0.01,0.0,0.0,0.0,0.0,7.0,9,0.250007,False,REGULAR,USD
41,AAPL260622C00365000,2026-06-15 15:07:26+00:00,365.0,0.45,0.0,0.0,0.0,0.0,NaN,4,0.500005,False,REGULAR,USD

In [188]:
puts = ticker.option_chain(expiry_date).puts
puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260622P00225000,2026-06-16 19:24:51+00:00,225.0,0.02,0.0,0.0,0.0,0.0,64.0,69,0.500005,False,REGULAR,USD
1,AAPL260622P00230000,2026-06-17 18:59:08+00:00,230.0,0.01,0.0,0.0,0.0,0.0,1.0,14,0.500005,False,REGULAR,USD
2,AAPL260622P00235000,2026-06-17 17:46:49+00:00,235.0,0.02,0.0,0.0,0.0,0.0,1.0,2,0.500005,False,REGULAR,USD
3,AAPL260622P00240000,2026-06-12 18:27:51+00:00,240.0,0.08,0.0,0.0,0.0,0.0,NaN,8,0.500005,False,REGULAR,USD
4,AAPL260622P00245000,2026-06-16 19:58:49+00:00,245.0,0.19,0.0,0.0,0.0,0.0,5.0,237,0.250007,False,REGULAR,USD
5,AAPL260622P00250000,2026-06-17 19:49:24+00:00,250.0,0.03,0.0,0.0,0.0,0.0,9.0,155,0.250007,False,REGULAR,USD
6,AAPL260622P00255000,2026-06-15 14:16:34+00:00,255.0,0.04,0.0,0.0,0.0,0.0,30.0,42,0.250007,False,REGULAR,USD
7,AAPL260622P00260000,2026-06-17 17:12:01+00:00,260.0,0.06,0.0,0.0,0.0,0.0,2.0,174,0.250007,False,REGULAR,USD
8,AAPL260622P00262500,2026-06-17 17:12:01+00:00,262.5,0.11,0.0,0.0,0.0,0.0,2.0,13,0.250007,False,REGULAR,USD
9,AAPL260622P00265000,2026-06-17 17:56:54+00:00,265.0,0.04,0.0,0.0,0.0,0.0,51.0,71,0.250007,False,REGULAR,USD
10,AAPL260622P00267500,2026-06-17 16:36:34+00:00,267.5,0.10,0.0,0.0,0.0,0.0,10.0,15,0.250007,False,REGULAR,USD
11,AAPL260622P00270000,2026-06-17 14:47:57+00:00,270.0,0.05,0.0,0.0,0.0,0.0,3.0,38,0.125009,False,REGULAR,USD
12,AAPL260622P00272500,2026-06-15 15:45:34+00:00,272.5,0.20,0.0,0.0,0.0,0.0,3.0,49,0.125009,False,REGULAR,USD
13,AAPL260622P00275000,2026-06-17 19:17:51+00:00,275.0,0.09,0.0,0.0,0.0,0.0,16.0,202,0.125009,False,REGULAR,USD
14,AAPL260622P00277500,2026-06-17 18:42:38+00:00,277.5,0.14,0.0,0.0,0.0,0.0,16.0,91,0.125009,False,REGULAR,USD
15,AAPL260622P00280000,2026-06-17 19:56:54+00:00,280.0,0.21,0.0,0.0,0.0,0.0,1258.0,1317,0.125009,False,REGULAR,USD
16,AAPL260622P00282500,2026-06-17 19:59:11+00:00,282.5,0.21,0.0,0.0,0.0,0.0,21.0,176,0.125009,False,REGULAR,USD
17,AAPL260622P00285000,2026-06-17 19:59:04+00:00,285.0,0.32,0.0,0.0,0.0,0.0,1495.0,1022,0.062509,False,REGULAR,USD
18,AAPL260622P00287500,2026-06-17 19:59:52+00:00,287.5,0.54,0.0,0.0,0.0,0.0,548.0,464,0.062509,False,REGULAR,USD
19,AAPL260622P00290000,2026-06-17 19:59:18+00:00,290.0,0.83,0.0,0.0,0.0,0.0,7666.0,6938,0.031260,False,REGULAR,USD
20,AAPL260622P00292500,2026-06-17 19:59:29+00:00,292.5,1.40,0.0,0.0,0.0,0.0,2643.0,1648,0.031260,False,REGULAR,USD
21,AAPL260622P00295000,2026-06-17 19:59:54+00:00,295.0,2.25,0.0,0.0,0.0,0.0,4450.0,1652,0.007822,False,REGULAR,USD
22,AAPL260622P00297500,2026-06-17 19:59:41+00:00,297.5,3.70,0.0,0.0,0.0,0.0,1745.0,1396,0.000010,True,REGULAR,USD
23,AAPL260622P00300000,2026-06-17 19:52:42+00:00,300.0,5.77,0.0,0.0,0.0,0.0,5269.0,1436,0.000010,True,REGULAR,USD
24,AAPL260622P00302500,2026-06-17 19:57:17+00:00,302.5,7.30,0.0,0.0,0.0,0.0,200.0,99,0.000010,True,REGULAR,USD
25,AAPL260622P00305000,2026-06-17 19:59:36+00:00,305.0,9.41,0.0,0.0,0.0,0.0,156.0,226,0.000010,True,REGULAR,USD
26,AAPL260622P00307500,2026-06-17 15:56:56+00:00,307.5,9.35,0.0,0.0,0.0,0.0,121.0,50,0.000010,True,REGULAR,USD
27,AAPL260622P00310000,2026-06-17 18:12:26+00:00,310.0,14.04,0.0,0.0,0.0,0.0,622.0,127,0.000010,True,REGULAR,USD
28,AAPL260622P00312500,2026-06-17 14:04:08+00:00,312.5,13.00,0.0,0.0,0.0,0.0,18.0,0,0.000010,True,REGULAR,USD
29,AAPL260622P00315000,2026-06-16 16:57:24+00:00,315.0,15.68,0.0,0.0,0.0,0.0,121.0,0,0.000010,True,REGULAR,USD
30,AAPL260622P00320000,2026-06-08 19:23:34+00:00,320.0,18.25,0.0,0.0,0.0,0.0,26.0,0,0.000010,True,REGULAR,USD
31,AAPL260622P00325000,2026-06-09 14:28:07+00:00,325.0,32.63,0.0,0.0,0.0,0.0,28.0,0,0.000010,True,REGULAR,USD
32,AAPL260622P00330000,2026-06-08 17:37:44+00:00,330.0,18.80,0.0,0.0,0.0,0.0,24.0,0,0.000010,True,REGULAR,USD
33,AAPL260622P00335000,2026-06-08 17:37:38+00:00,335.0,23.00,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
34,AAPL260622P00340000,2026-06-08 13:55:57+00:00,340.0,28.05,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
35,AAPL260622P00345000,2026-06-08 13:55:57+00:00,345.0,32.90,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
36,AAPL260622P00350000,2026-06-08 13:55:57+00:00,350.0,37.80,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
37,AAPL260622P00355000,2026-06-08 13:55:40+00:00,355.0,42.55,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD

In [189]:
S = ticker.fast_info['lastPrice']
print(S)

295.95001220703125

In [190]:
ticker_tnx = yf.Ticker("^TNX")

In [191]:
data = ticker_tnx.history(period="1d")
r = data['Close'].iloc[0]/100
print(r)

0.044630002975463864

In [192]:
log_returns = np.log(ticker.history(period='18mo')['Close']/ticker.history(period='18mo')['Close'].shift(1))
log_returns = log_returns.tail(252)
sigma = log_returns.std() * np.sqrt(252)
sigma

np.float64(0.22613619396832096)

In [193]:
calls['ATM'] = abs(calls['strike'] - S)
K = calls[calls['ATM']==calls['ATM'].min()]['strike'].iloc[0]
calls[calls['ATM']==calls['ATM'].min()]

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,ATM
19,AAPL260622C00295000,2026-06-17 19:59:41+00:00,295.0,3.36,0.0,0.0,0.0,0.0,1133.0,1254,0.00001,True,REGULAR,USD,0.950012

In [194]:
puts['ATM'] = abs(puts['strike'] - S)
puts[puts['ATM']==puts['ATM'].min()]

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,ATM
21,AAPL260622P00295000,2026-06-17 19:59:54+00:00,295.0,2.25,0.0,0.0,0.0,0.0,4450.0,1652,0.007822,False,REGULAR,USD,0.950012

In [195]:
d_1 = (np.log(S/K)+(r+sigma**2/2)*T)/(sigma*T)
d_2 = d_1 - sigma*T
print(d_1,d_2)

1.6078202131545947 1.6053420082891885

In [196]:
call_delta = scipy.stats.norm.pdf(d_1)
put_delta = call_delta-1
Gamma = scipy.stats.norm.cdf(d_1)/(S*sigma*np.sqrt(T))
call_theta = -(S*scipy.stats.norm.cdf(d_1)*sigma)/(2*np.sqrt(T)) - (r*K*((np.e)**(-r*T))*scipy.stats.norm.pdf(d_2))
put_theta = -(S*scipy.stats.norm.cdf(d_1)*sigma)/(2*np.sqrt(T)) + (r*K*((np.e)**(-r*T))*scipy.stats.norm.pdf(-d_2))
vega = S*np.sqrt(T)*scipy.stats.norm.cdf(d_1)

In [197]:
df = pd.DataFrame({"Option Type": ['CAll', 'PUT'], "Delta":[call_delta,put_delta], "Gamma": [Gamma, Gamma], "Theta": [call_theta,put_theta], "Vega": [vega,vega]}).set_index("Option Type")
df

                Delta     Gamma       Theta       Vega
Option Type
CAll         0.109538  0.135035 -303.856278  29.310407
PUT         -0.890462  0.135035 -300.961859  29.310407